// course-code/gz1703/Vue/day04/project/src/components/light/light.vue
<template>
    <div>
        <input type="button" :value="color" @click="changeLight" />
        <img :src="'./src/assets/imgs/' + color + '.jpg'" />
        <div>
            <childlight ref="ch"></childlight>
        </div>
    </div>
</template>

<script>
    import childlight from './childLight.vue'
    // import './light.scss';
    export default {
        name: 'light',
        data: function(){
            return {
                color: 'red',
                show: true
            }
        },
        methods: {
            changeLight: function(){
                console.log(this);
                this.color = this.color == 'red' ? 'green' : this.color == 'green' ? 'yellow' : 'red';
            }
        },
        components: {
            childlight
        }
    }
</script>

// course-code/gz1703/React/day03/redux/src/modules/light/lightComponent.js
import React from 'react';
import {connect} from 'react-redux';
import * as lightActions from './lightAction';
import './light.scss';

class LightComponent extends React.Component{
    render(){
        return (
            <div>
                <img src={'./src/static/images/' + this.props.color + '.jpg'}/>
                <br />
                <input type="button" value="red" onClick={this.props.changeRed}/>
                <input type="button" value="green" onClick={this.props.changeGreen} />
                <input type="button" value="yellow" onClick={this.props.changeYellow} />
            </div>
        )
    }
}

const mapStateToPorps = state => ({
    color: state.color
})

// props => action & state
export default connect(mapStateToPorps, lightActions)(LightComponent);
