// course-code/gz1703/Vue/day04/project/src/components/light2/light.vue
<template>
    <div>
        <input type="button" :value="color" @click="changeLight" />
        <img :src="'./src/assets/imgs/' + this.$store.state.aa.color + '.jpg'" />
    </div>
</template>

<script>
    // import childlight from './childLight.vue'
    // import './light.scss';
    // import { mapGetters, mapActions } from 'vuex'
    export default {
        name: 'light',
        data: function(){
            return {
                color: 'red',
            }
        },
        methods: {
            changeLight: function(){
                // console.log(this);
                // this.color = this.color == 'red' ? 'green' : this.color == 'green' ? 'yellow' : 'red';
                this.$store.dispatch('changeLight', 1);
                console.log('component', this);
            }
        }
    }
</script>

// course-code/gz1703/React/day03/redux/src/modules/light/lightComponent.js
import React from 'react';
import {connect} from 'react-redux';
import * as lightActions from './lightAction';
import './light.scss';

class LightComponent extends React.Component{
    render(){
        return (
            <div>
                <img src={'./src/static/images/' + this.props.color + '.jpg'}/>
                <br />
                <input type="button" value="red" onClick={this.props.changeRed}/>
                <input type="button" value="green" onClick={this.props.changeGreen} />
                <input type="button" value="yellow" onClick={this.props.changeYellow} />
            </div>
        )
    }
}

const mapStateToPorps = state => ({
    color: state.color
})

// props => action & state
export default connect(mapStateToPorps, lightActions)(LightComponent);
