// course-code/gz1701/react/src/component/light/LightComponent.js
import React, {Component} from 'react'
import LightAction from './LightAction'
import LightStore from './LightStore'


class LightComponent extends Component{
    state = {
        src: 'red'
    }
    change(event){
        LightAction(event.target.value)
    }
    componentDidMount(){
        LightStore.addEvent(function(){
            this.setState({src: LightStore.type})
        }.bind(this))
    }
    render(){
        //view
        return (
            <div>
                <input type="button"  value="red" onClick={this.change.bind(this)} />
                <input type="button"  value="green" onClick={this.change.bind(this)} />
                <input type="button"  value="yellow" onClick={this.change.bind(this)} />
                <img src={`./imgs/${this.state.src}.jpg`} alt="" />
            </div>
        )
    }
}

export default LightComponent

// course-code/gz1703/Vue/day04/project/src/components/light2/light.vue
<template>
    <div>
        <input type="button" :value="color" @click="changeLight" />
        <img :src="'./src/assets/imgs/' + this.$store.state.aa.color + '.jpg'" />
    </div>
</template>

<script>
    // import childlight from './childLight.vue'
    // import './light.scss';
    // import { mapGetters, mapActions } from 'vuex'
    export default {
        name: 'light',
        data: function(){
            return {
                color: 'red',
            }
        },
        methods: {
            changeLight: function(){
                // console.log(this);
                // this.color = this.color == 'red' ? 'green' : this.color == 'green' ? 'yellow' : 'red';
                this.$store.dispatch('changeLight', 1);
                console.log('component', this);
            }
        }
    }
</script>
